# Generated by Django 2.2.6 on 2019-11-08 16:32

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='название')),
                ('auditoria', models.BooleanField(default=True, verbose_name='аудитория')),
                ('longitude', models.IntegerField(verbose_name='широта')),
                ('latitude', models.IntegerField(verbose_name='долгота')),
            ],
            options={
                'verbose_name': 'кабинет',
                'verbose_name_plural': 'кабинеты',
                'db_table': 'cabinet',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
            ],
            options={
                'verbose_name': 'ученая степень',
                'verbose_name_plural': 'ученые степени',
                'db_table': 'degree',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('degree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Degree', verbose_name='ученая степень')),
            ],
            options={
                'verbose_name': 'сотрудник',
                'verbose_name_plural': 'сотрудники',
                'db_table': 'employee',
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField(verbose_name='номер')),
            ],
            options={
                'verbose_name': 'этаж',
                'verbose_name_plural': 'этажи',
                'db_table': 'floor',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'должность',
                'verbose_name_plural': 'должности',
                'db_table': 'position',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_from', models.TimeField(default=main.models.get_current_time, verbose_name='от')),
                ('time_to', models.TimeField(default=main.models.get_current_time, verbose_name='до')),
                ('weekday', models.IntegerField(choices=[(0, 'Пн'), (1, 'Вт'), (2, 'Ср'), (3, 'Чт'), (4, 'Пт'), (5, 'Сб'), (6, 'Вс')], verbose_name='день недели')),
                ('week_type', models.IntegerField(choices=[(0, 'Все'), (1, 'Чс'), (2, 'Зн')], default=0, verbose_name='тип недели')),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Cabinet')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Employee')),
            ],
            options={
                'verbose_name': 'расписание',
                'verbose_name_plural': 'расписание',
                'db_table': 'schedule',
            },
        ),
        migrations.CreateModel(
            name='PosHeld',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Employee', verbose_name='сотрудник')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Position', verbose_name='сотрудники')),
            ],
            options={
                'verbose_name': 'занимаемая должность',
                'verbose_name_plural': 'занимаемые должности',
                'db_table': 'posheld',
            },
        ),
        migrations.AddField(
            model_name='cabinet',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Floor', verbose_name='этаж'),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Cabinet', verbose_name='выход'),
        ),
    ]
